services:
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./web-app/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  machine-learning-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    env_file:
      - ./machine-learning-client/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
